<?php if(Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_loader_active')): ?>
<script type="text/javascript">
jQuery.ias({
  container 	: "<?php echo Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_container'); ?>",
  		// Enter the selector of the element containing
  		// your items that you want to paginate.
 
  item		: "<?php echo Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_item'); ?>",
		// Enter the selector of the element that each
		// item has. Make sure the elements are inside
		// the container element.
 
  pagination	: "<?php echo Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_pagination'); ?>",
		// Enter the selector of the element that contains
		// your regular pagination links, like next,
		// previous and the page numbers. This element
		// will be hidden when IAS loads.
 
  next		: "<?php echo Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_next'); ?>",
		// Enter the selector of the link element that
		// links to the next page. The href attribute
		// of this element will be used to get the items
		// from the next page.
 
  loader	: "<img src='<?php echo $this->getUrl(); ?><?php echo Mage::getStoreConfig('infinite_scroll/infinite_scroll_settings/scroll_loader'); ?>' style='margin-left:48%'/>"
		// Enter the url to the loader image. This image
		// will be displayed when the next page with items
		// is loaded via AJAX.
});
</script>
<?php endif; ?>