<?php
/**
 * @see RLM_Slider_Block_Slides
 * @var $this RLM_Slider_Block_Slides
 */
?>

<div class="logo-large"></div>
<ul class="slider">
    <?php foreach ($this->getSlides() as $slide): ?>
        <li style="background:url('<?php echo $this->getSlideUrl($slide); ?>');"></li>
    <?php endforeach; ?>
</ul>
<div class="sliderNav">
    <a id="prevSlide" class="btnSlide" href="#"></a>
    <a id="nextSlide" class="btnSlide" href="#"></a>
</div>

<script type="text/javascript">
	logoInUse = false;

    jQuery('document').ready(function() {
        jQuery('.slider').cycle({ 
            fx:     'scrollHorz', 
            speed:  'slow', 
            timeout: 0, 
            next:   '#nextSlide', 
            prev:   '#prevSlide' 
        });

        var top = (jQuery(window).height()-130)/2;
        jQuery('.logo-large').css({'top' : top})
        var top = (jQuery(window).height()-64)/2;
        jQuery('.sliderNav').css({'top' : top})
    });

    jQuery(window).resize(function(){
        var top = (jQuery(window).height()-130)/2;
        jQuery('.logo-large').css({'top' : top })
        var top = (jQuery(window).height()-64)/2;
        jQuery('.sliderNav').css({'top' : top})
		jQuery('.slider').children('li').each(function(){
			jQuery(this).css({ 'width' : jQuery(window).width() })
		})
    })

    jQuery('.logo-large').on('mouseenter', function(){
    	if (logoInUse == false){
    		logoInUse = true;
    		jQuery(this).animate({ 'opacity': "1"}, 2500,function(){
    			jQuery(this).animate({ 'opacity': "0"}, 2000,function(){
    				logoInUse = false;
    			})
    		})
    	}
    })
</script>
