<?php
/**
 * Scandiweb - creating a better future
 *
 * Scandi_VisualAttributes
 *
 * @category    Scandi
 * @package     Scandi_VisualAttributes
 * @author      Scandiweb.com <info@scandiweb.com>
 * @copyright   Copyright (c) 2013 Scandiweb.com (http://www.scandiweb.com)
 * @license     http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 3.0)
 */

/**
 * Template for attribute filter items with image display
 *
 * @var $this Scandi_VisualAttributes_Block_Catalog_Layer_Filter_Attribute
 */
?>
<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <li <?php echo $this->getImageHeight() ? "style=\"line-height:{$this->getImageHeight()}px;\"" : '' ?>>
            <?php $imageUrl = $this->getItemImage($_item) ?>
            <?php if ($imageUrl): ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" class="filter-item-image"><img src="<?php echo $imageUrl ?>" title="<?php echo $_item->getLabel() ?>" <?php echo $this->getImageWidth() ? "width=\"{$this->getImageWidth()}\"" : '' ?> <?php echo $this->getImageHeight() ? "height=\"{$this->getImageHeight()}\"" : '' ?>/></a>
            <?php endif; ?>

            <span class="filter-item-label <?php echo $imageUrl ? '' : 'no-image' ?>">
                <?php if ($_item->getCount() > 0): ?>
                    <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
                <?php else:?>
                    <?php echo $_item->getLabel() ?>
                <?php endif; ?>

                <?php if ($this->shouldDisplayProductCount()): ?>
                    (<?php echo $_item->getCount() ?>)
                <?php endif; ?>
            </span>
        </li>
    <?php endforeach ?>
</ol>
