<?php
/**
 * Home page container for hiden forms sign in/register/reset pass
 *
 * @see Mage_Core_Block_Template
 */
?>

<div class="overflow-bg"></div>

<div id="sign_in" class="sign-in popup">
    <span class="close"></span>
    sign in
    <a id="forgot-password" href="#"><?php echo $this->__('Forgot password?') ?></a>
    <a id="create-new" href="#"><?php echo $this->__('Create new account') ?></a>
</div>

<div id="create_new" class="create-new popup">
    <span class="close"></span>
    create new
</div>

<div id="reset-pass" class="reset-pass popup">
    <span class="close"></span>
    reset pass
</div>
